kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: drupal-files
  labels:
    app: drupal
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: drupal-files-nfs-server
  labels:
    app: drupal
spec:
  replicas: 1
  template:
    metadata:
      labels:
        role: nfs-server
    spec:
      containers:
        - name:  drupal-files-nfs-server
          image: gcr.io/google_containers/volume-nfs:0.8
          ports:
            - name: nfs
              containerPort: 2049
            - name: mountd
              containerPort: 20048
            - name: rpcbind
              containerPort: 111
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /exports
              name: drupal-files
      volumes:
        - name: drupal-files
          persistentVolumeClaim:
            claimName: drupal-files
---
apiVersion: v1
kind: Service
metadata:
  name:  drupal-files-nfs-server
spec:
  ports:
    - name: nfs
      port: 2049
    - name: mountd
      port: 20048
    - name: rpcbind
      port: 111
  selector:
    role: nfs-server
