kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: drupal-database
  labels:
    app: drupal
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: drupal-database
  labels:
    app: drupal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drupal-db
  template:
    metadata:
      labels:
        app: drupal-db
        role: db-server
    spec:
      containers:
        - name: drupal-database-server
          image: mariadb:latest
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: drupal-database-vol
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cloudsql-db-credentials
                  key: root-password
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: cloudsql-db-credentials
                  key: username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cloudsql-db-credentials
                  key: password
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: cloudsql-db-credentials
                  key: dbname
      volumes:
        - name: drupal-database-vol
          persistentVolumeClaim:
            claimName: drupal-database
        - name: cloudsql-db-credentials
          secret:
            secretName: cloudsql-db-credentials
---
apiVersion: v1
kind: Service
metadata:
  name:  drupal-db-server
spec:
  ports:
    - port: 3306
  selector:
    role: db-server
