apiVersion: v1
kind: PersistentVolume
metadata:
  name: apigee-devportal-drupal-files
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: a.b.c.d
    path: /portal_files
    readOnly: false
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: apigee-devportal-drupal-files
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 50Gi