apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-drupal-files
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: <IP_ADDRESS>
    path: <PATH>
    readOnly: false
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-drupal-files
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 10Gi
---